'use client';
import {useState,useEffect,useRef,useMemo} from 'react';
import {BookOpen,Home,GraduationCap,Languages,Mic,Headphones,PenLine,Target,RotateCcw,BarChart3,Sparkles,Settings,Search,Flame,Volume2,Bookmark,Check,ChevronRight,Clock,LayoutGrid,Shield,Upload,Download,Trash2,Sun,Moon,MessageCircle,CheckCircle2,AlertCircle,LogOut,Play,Plus,FileText,Trophy,X,Keyboard,MoreHorizontal} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarGroup,SidebarGroupLabel,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {Progress} from '@/components/ui/progress';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Toaster,toast} from 'sonner';
import * as E from '@/lib/engine';
import type {Profile,Word,Question,Dimension} from '@/lib/engine';
import {grammarTopics,grammarQuestions,bookQuestions} from '@/lib/grammar';
import {readProfile,writeProfile,download} from '@/lib/storage';

const navGroups=[{label:'O‘QUV MAYDONI',items:[['home','Bosh sahifa',Home],['units','Kitob Unitlari',BookOpen],['learn','O‘rganish',GraduationCap],['vocabulary','So‘zlar',Languages]]},{label:'KO‘NIKMALAR',items:[['grammar','Grammatika',FileText],['pronunciation','Talaffuz',Mic],['listening','Tinglash',Headphones],['speaking','Gapirish',MessageCircle],['writing','Yozish',PenLine]]},{label:'MUSTAHKAMLASH',items:[['practice','Mashqlar',LayoutGrid],['mastery','Mastery',Target],['review','Takrorlash',RotateCcw],['mistakes','Xatolarim',AlertCircle],['mock','Sinov testi',CheckCircle2],['progress','Natijalar',BarChart3],['tutor','AI Tutor',Sparkles]]}];
const englishLabels:Record<string,string>={home:'Home',units:'Book Units',learn:'Learn',vocabulary:'Vocabulary',grammar:'Grammar',pronunciation:'Pronunciation',listening:'Listening',speaking:'Speaking',writing:'Writing',practice:'Practice',mastery:'Mastery',review:'Review',mistakes:'Mistakes',mock:'Mock Test',progress:'Progress',tutor:'AI Tutor',profile:'Profile',settings:'Settings',weak:'Weak Words',weakpron:'Weak Pronunciation'};
const dimNames:Record<Dimension,string>={englishToUzbek:'English → Uzbek',uzbekToEnglish:'Uzbek → English',listening:'Tinglash',spelling:'Imlo',pronunciation:'Talaffuz',context:'Kontekst'};
const levelNames=['O‘rganilmagan','Ko‘rilgan','O‘rganilmoqda','Esda qolmoqda','Mustahkam','Mastered'];
function Pick({value,onChange,items}:{value:string;onChange:(v:string)=>void;items:[string,string][]}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="pick"><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,n])=><SelectItem value={v} key={v}>{n}</SelectItem>)}</SelectContent></Select>;}
function Bar({value}:{value:number}){return <Progress value={value} className="meter"/>;}
function Source({book=false}:{book?:boolean}){return <span className={'source '+(book?'book':'extra')}>{book?<BookOpen size={13}/>:<Sparkles size={13}/>} {book?'Essential Book':'Extra Practice'}</span>;}
function Empty({title,text,action}:{title:string;text:string;action?:React.ReactNode}){return <div className="empty-state"><BookOpen size={30}/><h3>{title}</h3><p>{text}</p>{action}</div>;}
function Stat({icon:Icon,value,label}:{icon:any;value:string|number;label:string}){return <div className="stat"><span className="stat-icon"><Icon size={19}/></span><div><strong>{value}</strong><span>{label}</span></div></div>;}

export default function Page(){
 const [profile,setProfile]=useState<Profile|null>(null),[loaded,setLoaded]=useState(false),[view,setView]=useState('home'),[search,setSearch]=useState(''),[fn,setFn]=useState(''),[ln,setLn]=useState(''),[savingError,setSavingError]=useState('');
 const [wordIndex,setWordIndex]=useState(0),[learnStep,setLearnStep]=useState(0),[listened,setListened]=useState(false),[attempted,setAttempted]=useState(false),[speechState,setSpeechState]=useState(''),[detected,setDetected]=useState(''),[selectedWord,setSelectedWord]=useState<Word|null>(null),[exampleIndex,setExampleIndex]=useState(0),[lessonRun,setLessonRun]=useState(0);
 const [session,setSession]=useState<{questions:Question[];index:number;mode:string;correct:number;answers:{q:Question;answer:string;ok:boolean}[];done:boolean;deadline?:number;nextUnit?:number}|null>(null),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState<{ok:boolean;q:Question}|null>(null),[hint,setHint]=useState(0),[confidence,setConfidence]=useState('3'),[timer,setTimer]=useState(0),[format,setFormat]=useState('mixed'),[grammarId,setGrammarId]=useState('present-simple'),[mockCount,setMockCount]=useState('20'),[resetOpen,setResetOpen]=useState(false);
 const [writing,setWriting]=useState(''),[writingTopic,setWritingTopic]=useState('My family'),[writingFeedback,setWritingFeedback]=useState(''),[aiBusy,setAiBusy]=useState(false),[tutorText,setTutorText]=useState(''),[messages,setMessages]=useState<{role:string;text:string}[]>([{role:'assistant',text:'Salom! Unit so‘zlari, tarjima yoki grammatikadan mashq qilamiz. Masalan: “O‘zbekchadan English so‘ra”.'}]);
 const [adminDraft,setAdminDraft]=useState(''),[adminFilter,setAdminFilter]=useState(''),[generated,setGenerated]=useState<Question[]>([]),[genCount,setGenCount]=useState('10'),[importInfo,setImportInfo]=useState(''),[editWord,setEditWord]=useState<Word|null>(null),[draftWord,setDraftWord]=useState(''),[draftUz,setDraftUz]=useState(''),[draftMeaning,setDraftMeaning]=useState(''),[draftExample,setDraftExample]=useState(''),[unitTitle,setUnitTitle]=useState(''),[questionDraft,setQuestionDraft]=useState(''),[connectionStatus,setConnectionStatus]=useState('');
 const [micBusy,setMicBusy]=useState(false),[audioUrl,setAudioUrl]=useState('');
 const mediaRef=useRef<MediaRecorder|null>(null),audioRef=useRef(''),streamRef=useRef<MediaStream|null>(null),recordTimeout=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{mediaRef.current?.state==='recording'&&mediaRef.current.stop();streamRef.current?.getTracks().forEach(t=>t.stop());if(audioRef.current)URL.revokeObjectURL(audioRef.current);if(recordTimeout.current)clearTimeout(recordTimeout.current);},[]);
 const profileRef=useRef<Profile|null>(null),startTime=useRef(Date.now()),recognitionRef=useRef<any>(null),timerRef=useRef<ReturnType<typeof setInterval>|null>(null),tutorQuestion=useRef<Question|null>(null);
 useEffect(()=>{(async()=>{try{const id=localStorage.getItem('essential-active');if(id){const p=await readProfile(id);if(p)setProfile(E.restoreDefaults(p));}}catch{setSavingError('Saqlangan ma’lumotni ochib bo‘lmadi. Brauzerda saqlashga ruxsat bering.');}setLoaded(true);})();return ()=>recognitionRef.current?.abort();},[]);
 useEffect(()=>{if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);
 useEffect(()=>{profileRef.current=profile;if(profile){const t=setTimeout(()=>{writeProfile(profile).then(()=>setSavingError('')).catch(()=>setSavingError('Natijani saqlab bo‘lmadi. Qurilmada bo‘sh joyni tekshiring va zaxira yuklab oling.'));},180);return ()=>clearTimeout(t);}},[profile]);
 useEffect(()=>{if(!profile)return;let last=Date.now();const id=setInterval(()=>{const now=Date.now();if(document.visibilityState==='visible')setProfile(p=>p?{...p,studySeconds:p.studySeconds+Math.min(15,Math.round((now-last)/1000)),daySeconds:{...p.daySeconds,[E.dateKey()]:(p.daySeconds?.[E.dateKey()]||0)+Math.min(15,Math.round((now-last)/1000))}}:p);last=now;},15000);return ()=>clearInterval(id);},[profile?.id]);
 useEffect(()=>{if(!profile)return;const dark=profile.settings.theme==='dark'||profile.settings.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches;const odina=E.norm(profile.firstName)==='odina'&&E.norm(profile.lastName)==='namozova';document.documentElement.classList.toggle('dark',dark||odina);document.documentElement.classList.toggle('odina',odina);},[profile?.id,profile?.settings.theme]);
 useEffect(()=>{if(!session?.deadline||session.done)return;const tick=()=>{const left=Math.max(0,Math.ceil((session.deadline!-Date.now())/1000));setTimer(left);if(left===0){setSession(s=>s?{...s,done:true}:s);}};tick();const t=setInterval(tick,250);return()=>clearInterval(t);},[session?.deadline,session?.done]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const abort=new AbortController();const tools=[{name:'read_learning_progress',title:'Learning progress',description:'Read the active learner’s saved progress.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>{const p=profileRef.current;if(!p)throw new Error('Enter your name first');return {currentUnit:p.currentUnit,studied:p.studied,answered:p.answered,accuracy:E.accuracy(p),mastery:E.overall(p)};}},{name:'open_learning_section',title:'Open learning section',description:'Open a learning section without answering or completing exercises.',inputSchema:{type:'object',properties:{section:{type:'string',enum:['home','units','learn','vocabulary','review','progress']}},required:['section'],additionalProperties:false},execute:(input:any)=>{if(!profileRef.current)throw new Error('Enter your name first');if(!['home','units','learn','vocabulary','review','progress'].includes(input?.section))throw new Error('Invalid section');setSession(null);setView(input.section);return {opened:input.section};}}];for(const t of tools){try{Promise.resolve(ctx.registerTool(t,{signal:abort.signal})).catch(()=>{});}catch{}}return()=>abort.abort();},[]);
 const allUnits=profile?[...E.units.map(u=>({...u,title:profile.unitNames[u.id]||u.title})),...profile.customUnits].filter(u=>!profile.hiddenUnits.includes(u.id)):E.units;
 const allWords=profile?[...E.words.filter(w=>!profile.imports.some(i=>i.id===w.id&&i.verified)),...profile.imports.filter(w=>w.verified)].filter(w=>!profile.hiddenWords.includes(w.id)&&!profile.hiddenUnits.includes(w.unit)):E.words;
 const currentWords=allWords.filter(w=>w.unit===(profile?.currentUnit||1));const activeWord=currentWords[wordIndex%Math.max(1,currentWords.length)];
 const due=profile?E.pool(profile,'due',allWords):[],weak=profile?E.pool(profile,'weak',allWords).filter(w=>E.mastery(profile.wp[w.id])<75):[],old=profile?E.pool(profile,'previous',allWords):[];
 const isOdina=profile&&E.norm(profile.firstName)==='odina'&&E.norm(profile.lastName)==='namozova';
 const title=view==='weak'?'Zaif so‘zlar':view==='weakpron'?'Zaif talaffuz':view==='profile'?'Profil':view==='settings'?'Sozlamalar':navGroups.flatMap(g=>g.items).find(i=>i[0]===view)?.[1]||view;
 const label=(id:string,uz:string)=>profile?.settings.language==='en'?englishLabels[id]||uz:uz;
 function update(p:Profile){profileRef.current=p;setProfile(p);}
 function go(id:string){stopMic();setAudioUrl('');setSpeechState('');setView(id);setSession(null);setFeedback(null);setAnswer('');setHint(0);setSearch('');}
 async function login(e:React.FormEvent){e.preventDefault();if(!fn.trim()||!ln.trim())return;const p=E.newProfile(fn,ln);try{const saved=await readProfile(p.id);await writeProfile(saved||p);localStorage.setItem('essential-active',p.id);setProfile(saved?E.restoreDefaults(saved):p);setSavingError('');}catch{toast.error('Profil saqlanmadi. Brauzer xotirasiga ruxsat bering.');}}
 function speak(text:string){if(!profile?.settings.sound){toast('Ovoz sozlamalarda o‘chirilgan.');return;}if(!('speechSynthesis'in window)){toast.error('Bu brauzer ovozli o‘qishni qo‘llamaydi.');setSpeechState('Ovoz mavjud emas. Mustaqil takrorlashdan foydalaning.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=profile.settings.audioRate||.65;const voice=speechSynthesis.getVoices().find(v=>v.lang==='en-US');if(voice)u.voice=voice;u.onerror=()=>toast.error('Ovoz o‘qilmadi. Yana urinib ko‘ring.');speechSynthesis.speak(u);setListened(true);}
 function micError(code:string){return ({'not-allowed':'Mikrofon ruxsati yopiq. Brauzer manzil satridagi sayt sozlamalaridan Mikrofon → Ruxsat berish ni tanlang va sahifani yangilang.','service-not-allowed':'Brauzer nutqni tanish xizmatini blokladi. Saytni alohida Chrome tabida oching yoki ovoz yozishdan foydalaning.','network':'Nutqni tanish xizmatiga ulanish bo‘lmadi. Internetni tekshiring. Ovoz yozib qayta eshitish ishlashi mumkin.','audio-capture':'Mikrofon topilmadi yoki boshqa dastur ishlatyapti. Qurilma va Windows mikrofon ruxsatlarini tekshiring.','no-speech':'Nutq eshitilmadi. Mikrofon yoqilgandan keyin inglizcha ayting.','language-not-supported':'Brauzer inglizcha nutqni tanishni qo‘llamaydi. Ovoz yozishdan foydalaning.'} as Record<string,string>)[code]||'Nutqni tanish ishlamadi. Ovoz yozishdan foydalaning.';}
 function stopMic(){recognitionRef.current?.stop();if(mediaRef.current?.state==='recording')mediaRef.current.stop();}
 function record(expected?:string,word?:Word,free=false,quiz=false){
 if(micBusy){stopMic();return;}window.speechSynthesis?.cancel();const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;
 if(!SR){setSpeechState('Bu brauzer nutqni matnga aylantirmaydi. Ovoz yozib qayta eshitishdan foydalaning.');return;}
 recognitionRef.current?.abort();const r=new SR();recognitionRef.current=r;r.lang='en-US';r.interimResults=free;r.continuous=free;let finalText='';setDetected('');setMicBusy(true);setSpeechState('Mikrofon ochilmoqda…');
 r.onstart=()=>{if(recognitionRef.current===r)setSpeechState('Tinglayapman…');};
 r.onresult=(ev:any)=>{if(recognitionRef.current!==r)return;let interim='';for(let i=ev.resultIndex;i<ev.results.length;i++){const txt=ev.results[i][0].transcript;if(ev.results[i].isFinal)finalText+=(finalText?' ':'')+txt;else interim+=' '+txt;}const txt=(finalText+interim).trim();setDetected(txt);if(free){setWriting(txt);setSpeechState('Tinglayapman…');}else if(finalText){if(quiz)setAnswer(finalText);setAttempted(true);const score=E.similarity(expected||'',finalText);setSpeechState(`${score}% · ${score>=85?'Great':score>=70?'Good':score>=50?'Almost':'Try again'}`);if(word&&profileRef.current)update(E.pronounce(profileRef.current,word.id,score));}};
 r.onerror=(ev:any)=>{if(recognitionRef.current!==r)return;setMicBusy(false);if(ev.error!=='aborted')setSpeechState(micError(ev.error));};
 r.onend=()=>{if(recognitionRef.current!==r)return;setMicBusy(false);if(recordTimeout.current)clearTimeout(recordTimeout.current);setSpeechState(prev=>prev==='Tinglayapman…'||prev==='Mikrofon ochilmoqda…'?finalText?'Nutq matnga aylantirildi. Tekshirishingiz mumkin.':'Nutq aniqlanmadi. Ovoz yozish bilan mikrofonni sinang.':prev);};
 try{r.start();recordTimeout.current=setTimeout(()=>r.stop(),free?60000:15000);}catch{setMicBusy(false);setSpeechState('Mikrofon ishga tushmadi. Saytni alohida tabda oching va ruxsatni tekshiring.');}}
 async function captureAudio(){
 if(micBusy){stopMic();return;}recognitionRef.current?.abort();recognitionRef.current=null;window.speechSynthesis?.cancel();setDetected('');setSpeechState('Mikrofon ruxsatini kutyapman…');setMicBusy(true);
 try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('Unsupported');const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;const recorder=new MediaRecorder(stream);mediaRef.current=recorder;const chunks:BlobPart[]=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());setMicBusy(false);if(recordTimeout.current)clearTimeout(recordTimeout.current);if(audioRef.current)URL.revokeObjectURL(audioRef.current);const url=URL.createObjectURL(new Blob(chunks,{type:recorder.mimeType}));audioRef.current=url;setAudioUrl(url);setAttempted(true);setSpeechState('Ovoz yozildi. Qayta eshitib namunaga solishtiring. Bu yozuvga avtomatik talaffuz balli berilmaydi.');};recorder.start();setSpeechState('Ovoz yozilmoqda… Tugatish tugmasini bosing.');recordTimeout.current=setTimeout(()=>{if(recorder.state==='recording')recorder.stop();},30000);
 }catch(e){setMicBusy(false);streamRef.current?.getTracks().forEach(t=>t.stop());const name=e instanceof Error?e.name:'';setSpeechState(name==='NotAllowedError'?micError('not-allowed'):name==='NotFoundError'||name==='NotReadableError'?micError('audio-capture'):'Bu brauzer ovoz yozishni qo‘llamaydi. Saytni Chrome tabida oching.');}}
 function microphoneTools(){return <div className="card microphone-tools"><h3>Mikrofon va ovoz</h3><p>Nutqni tanish ishlamasa, ovozingizni yozib qayta eshiting. Yozuv qurilmangizda qoladi.</p><div className="row"><button className="btn secondary" disabled={micBusy} onClick={captureAudio}><Mic size={18}/> Ovoz yozish</button>{micBusy&&<button className="btn primary" onClick={stopMic}>Tugatish</button>}<a className="text-btn" href={typeof location==='undefined'?'/':location.href} target="_blank" rel="noopener noreferrer">Alohida tabda ochish</a></div>{speechState&&<p role="status">{speechState}</p>}{audioUrl&&<audio controls src={audioUrl} aria-label="Sizning ovoz yozuvingiz"/>}</div>;}
 function markSeen(w:Word){if(!profile)return;const p=structuredClone(profile);p.wp[w.id]=p.wp[w.id]||E.emptyWP();p.wp[w.id].seen=true;p.wp[w.id].nextReview=p.wp[w.id].nextReview||Date.now();update(p);}
 function startLearning(w?:Word){if(!w&&!activeWord){toast('Bu Unitga avval tasdiqlangan so‘z qo‘shing.');go('units');return;}go('learn');if(w){if(!profile)return;const p=structuredClone(profile);p.currentUnit=w.unit;p.studied=Array.from(new Set([...p.studied,w.unit]));p.wp[w.id]=p.wp[w.id]||E.emptyWP();p.wp[w.id].seen=true;p.wp[w.id].nextReview=p.wp[w.id].nextReview||Date.now();update(p);setWordIndex(allWords.filter(x=>x.unit===w.unit).findIndex(x=>x.id===w.id));}else if(activeWord)markSeen(activeWord);resetLearn();}
 function resetLearn(){setLearnStep(0);setLessonRun(run=>run+1);setExampleIndex(0);setListened(false);setAttempted(false);setDetected('');setSpeechState('');setAnswer('');setFeedback(null);}
 function startUnitTest(p=profile,nextUnit?:number){if(!p)return;stopMic();const questions=E.unitTestQuestions(p,allWords);if(!questions.length){toast('Bu Unitda tasdiqlangan so‘z yo‘q.');return;}setSession({questions,index:0,mode:'unit-test',correct:0,answers:[],done:false,nextUnit});setView('practice');setFeedback(null);setAnswer('');setHint(0);startTime.current=Date.now();}
 function startSession(mode:string,count=20,f=format,nextUnit?:number){if(!profile)return;if(mode==='unit-test'){startUnitTest(profile,nextUnit);return;}let qs:Question[]=[];if(mode==='grammar')qs=E.shuffle(grammarQuestions.filter(q=>q.topic===grammarId));else if(mode==='mistakes'){qs=profile.mistakes.filter(m=>!m.resolved).map(m=>{const saved=[...grammarQuestions,...bookQuestions,...profile.customQuestions].find(q=>q.id===m.id);if(saved)return saved;const w=allWords.find(w=>w.id===m.wordId);return w?E.makeQuestion(w,m.type,allWords):null;}).filter((q):q is Question=>!!q&&E.validateQuestion(q));}else if(mode==='book'){qs=E.shuffle(bookQuestions.filter(q=>q.unit===profile.currentUnit));}else if(mode==='final')qs=E.sessionQuestions(profile,'mock',100,'mixed',allWords);else qs=E.sessionQuestions(profile,mode==='perfect'?'current':mode,count,f,allWords);const custom=profile.customQuestions.filter(q=>q.unit===profile.currentUnit&&q.verified&&E.validateQuestion(q));if(mode==='current'&&custom.length)qs=E.shuffle([...qs,...custom]).slice(0,count);if(!qs.length){toast('Avval so‘zlarni “O‘rganish” bo‘limida o‘rganing.');return;}if(mode==='mock'&&qs.length<count)toast(`${qs.length} ta takrorlanmagan savol mavjud. Ko‘proq so‘z o‘rganib, uzunroq testni oching.`);setSession({questions:qs,index:0,mode,correct:0,answers:[],done:false,nextUnit,deadline:mode.startsWith('rapid')?Date.now()+Number(mode.slice(5))*1000:undefined});setFeedback(null);setAnswer('');setHint(0);startTime.current=Date.now();setView('practice');}
 function openUnit(id:number){if(!profile)return;if(id>profile.currentUnit&&currentWords.some(w=>profile.wp[w.id]?.seen)){const lastTest=profile.tests.some(t=>t.unit===profile.currentUnit);if(!lastTest){startUnitTest(profile,id);toast('Keyingi Unitdan oldin yakuniy testni bajaring.');return;}}update({...profile,currentUnit:id,studied:Array.from(new Set([...profile.studied,id]))});setWordIndex(0);resetLearn();go('unit');}
 function bookmark(id:string){if(!profile)return;update({...profile,bookmarks:profile.bookmarks.includes(id)?profile.bookmarks.filter(x=>x!==id):[...profile.bookmarks,id]});}
 const simpleExamples=activeWord?E.sentenceExamples(activeWord):[];
 const sentenceOrder=useMemo(()=>E.shuffle(simpleExamples.map((_,i)=>i)),[activeWord?.id,lessonRun]);
 const learnStages=activeWord?E.wordLessonStages(activeWord,sentenceOrder):[];
 const learnFormats=learnStages.map(stage=>stage.type);
 const learnQ=activeWord&&learnStep>0?E.makeQuestion(activeWord,learnStages[Math.min(learnStep-1,learnStages.length-1)].type,allWords,learnStages[Math.min(learnStep-1,learnStages.length-1)].i):null;
 const q=session&&!session.done?session.questions[session.index]:view==='learn'?learnQ:null;
 function submit(){if(!q||!profile||feedback||!answer.trim())return;const ok=E.checkAnswer(q,answer);update(E.answerResult(profile,q,answer,Date.now()-startTime.current,Number(confidence)));if(session){const answers=[...session.answers,{q,answer,ok}];const qs=[...session.questions];if(!ok&&session.mode!=='mock'&&session.mode!=='final'&&session.mode!=='unit-test'&&!session.mode.startsWith('rapid')){const retryAt=Math.min(qs.length,session.index+5);qs.splice(retryAt,0,q);}const s={...session,questions:qs,correct:session.correct+(ok?1:0),answers};if(session.mode==='mock'||session.mode==='final'||session.mode==='unit-test'||session.mode.startsWith('rapid')){if(s.index+1>=qs.length){finishSession(s);}else{setSession({...s,index:s.index+1});setAnswer('');setHint(0);startTime.current=Date.now();}}else{setSession(s);setFeedback({ok,q});}}else setFeedback({ok,q});}
 function finishSession(s:NonNullable<typeof session>){setSession({...s,done:true});setFeedback(null);if(profile&&(s.mode==='mock'||s.mode==='final'||s.mode==='unit-test'))update({...profileRef.current!,tests:[...profileRef.current!.tests,{at:Date.now(),score:s.correct,total:s.answers.length,final:s.mode==='final',...(s.mode==='unit-test'?{unit:profile.currentUnit,previousCount:s.questions.filter(q=>q.unit!==profile.currentUnit).length}:{})}]});}
 function nextQuestion(){recognitionRef.current?.abort();recognitionRef.current=null;setMicBusy(false);const retry=!session&&feedback&&!feedback.ok;setFeedback(null);setAnswer('');setHint(0);startTime.current=Date.now();if(retry)return;if(session){if(session.index+1>=session.questions.length)finishSession(session);else setSession({...session,index:session.index+1});}else if(learnStep<learnFormats.length)setLearnStep(learnStep+1);else{if(!profile||!activeWord)return;const completed=Array.from(new Set([...profile.flowCompleted,activeWord.id]));const p={...profile,flowCompleted:completed};update(p);resetLearn();const remaining=currentWords.findIndex(w=>!completed.includes(w.id));if(remaining<0){toast.success('Unit so‘zlari bajarildi. Yakuniy testni boshlaymiz.');const next=allUnits.find(u=>u.id>profile.currentUnit)?.id;startUnitTest(p,next);}else{toast.success('So‘z mashqlari bajarildi.');setWordIndex(remaining);}}}
 function learnerStart(){if(!profile||!activeWord)return;if(profile.settings.required&&(!attempted||!listened)){toast('Avval so‘zni eshiting va qaytarib ayting.');return;}markSeen(activeWord);setLearnStep(1);setFeedback(null);setAnswer('');startTime.current=Date.now();}
 function fallback(){setAttempted(true);setListened(true);if(profile&&activeWord)update(E.pronounce(profile,activeWord.id,0,true));setSpeechState('Mustaqil takrorlash qayd etildi. Talaffuz balli berilmadi.');}
 async function requestAI(task:string,input:string){const res=await fetch('/api/tutor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({history:messages.slice(-12),task,input,unit:profile?.currentUnit,words:currentWords.map(w=>({word:w.word,meaning:w.meaning,uzbek:w.uzbekMeaning})).slice(0,20)})});const data:any=await res.json();if(!res.ok)throw new Error(data.error||'AI javob bera olmadi.');return data;}
 async function checkWriting(){if(!writing.trim())return;setAiBusy(true);try{const r=await requestAI(view==='speaking'?'speaking':'writing',writing);setWritingFeedback(r.text);}catch(e){toast.error(e instanceof Error?e.message:'Gemini javob bera olmadi.');const fixes:[RegExp,string][]=[[/\bI is\b/gi,'I am'],[/\bShe go\b/gi,'She goes'],[/\bHe go\b/gi,'He goes'],[/\bI have went\b/gi,'I have gone'],[/\bI am agree\b/gi,'I agree'],[/\bcan to\b/gi,'can'],[/\bdid not went\b/gi,'did not go']];const found=fixes.filter(([r])=>r.test(writing));const corrected=fixes.reduce((s,[r,v])=>s.replace(r,v),writing);setWritingFeedback(`Qoidalar asosida dastlabki tekshiruv (Gemini javobi olinmadi).\n\n${writing.trim().split(/\s+/).length} ta so‘z, ${writing.split(/[.!?]+/).filter(s=>s.trim()).length} ta gap.\n${found.length?`Topilgan xatolar: ${found.length}.\nTuzatilgan shakl: ${corrected}`:'Aniq qoidalardagi xato topilmadi. Bu matn to‘liq to‘g‘ri degani emas.'}\n\nAI ulanishi ishlagach grammatika va tabiiylikni to‘liq tekshirish mumkin.`);}finally{setAiBusy(false);}}
 async function tutorSend(){const text=tutorText.trim();if(!text||!profile)return;setTutorText('');setMessages(m=>[...m,{role:'user',text}]);const tq=tutorQuestion.current;if(tq){const ok=E.checkAnswer(tq,text);update(E.answerResult(profile,tq,text,Date.now()-startTime.current));tutorQuestion.current=null;setMessages(m=>[...m,{role:'assistant',text:`${ok?'To‘g‘ri!':'To‘g‘ri javob: '+tq.correctAnswer+'.'} ${tq.explanation}\nKeyingi savol uchun “savol ber” deb yozing.`}]);return;}const n=E.norm(text);if(/savol|so‘ra|so'ra|quiz|test|weak|xato|oldingi/.test(n)){const match=n.match(/unit\s*(\d+)/);const unit=match?Number(match[1]):profile.currentUnit;if(!allUnits.some(u=>u.id===unit)){setMessages(m=>[...m,{role:'assistant',text:'Kitobda Unit 1–30 mavjud.'}]);return;}const mode=/weak|zaif/.test(n)?'weak':/xato/.test(n)?'mistakes':/oldingi/.test(n)?'previous':'current';const ws=mode==='current'?allWords.filter(w=>w.unit===unit):E.pool(profile,mode,allWords);if(!ws.length){setMessages(m=>[...m,{role:'assistant',text:'Bu ro‘yxat hali bo‘sh. Avval so‘zlarni o‘rganing.'}]);return;}const w=E.shuffle(ws)[0],qq=E.makeQuestion(w,/o.zbekchadan|uzbek.*english/.test(n)?'uz-en':'en-uz',allWords);tutorQuestion.current=qq;startTime.current=Date.now();setMessages(m=>[...m,{role:'assistant',text:qq.question}]);return;}if(/grammar|grammatika/.test(n)){const g=grammarTopics.find(g=>n.includes(g.name.toLowerCase()))||grammarTopics[0];setMessages(m=>[...m,{role:'assistant',text:`${g.name}\n${g.rule}\n${g.positive}\n${g.negative}\n${g.question}`}]);return;}if(/talaffuz|pronunciation/.test(n)){go('pronunciation');return;}if(/speaking|gapirish/.test(n)){go('speaking');return;}setAiBusy(true);try{const r=await requestAI('tutor',text);setMessages(m=>[...m,{role:'assistant',text:r.text}]);}catch(e){setMessages(m=>[...m,{role:'assistant',text:'Gemini javobi olinmadi. Sayt egasi AI ulanishini tekshirishi kerak. Hozir kitob so‘zlari va tekshirilgan qoidalar asosidagi tutor ishlaydi. “Savol ber”, “Grammar tushuntir” yoki “Weak words’dan so‘ra” deb yozing.'}]);}finally{setAiBusy(false);}}
 function addDraftWord(){if(!profile||!draftWord.trim()||!draftUz.trim()||!draftMeaning.trim()||!draftExample.trim()){toast.error('Barcha maydonlarni to‘ldiring.');return;}const w:Word={id:editWord?.id||`custom-${Date.now()}`,word:draftWord.trim(),unit:profile.currentUnit,meaning:draftMeaning.trim(),uzbekMeaning:draftUz.trim(),acceptedUzbekMeanings:draftUz.split(';').map(s=>s.trim()),partOfSpeech:editWord?.partOfSpeech||'',phonetic:'',example:draftExample.trim(),sourceType:'extra',verified:false,difficulty:1,page:0,sourceNote:'Kontent'};setProfile({...profile,imports:[...profile.imports.filter(x=>x.id!==w.id),w]});setEditWord(null);setDraftWord('');setDraftUz('');setDraftMeaning('');setDraftExample('');toast('So‘z tekshiruv navbatiga qo‘shildi.');}
 function openEdit(w:Word){setEditWord(w);setDraftWord(w.word);setDraftUz(w.acceptedUzbekMeanings.join(';'));setDraftMeaning(w.meaning);setDraftExample(w.example);}
 async function importFile(file:File){if(file.size>10*1024*1024){setImportInfo('Fayl 10 MB dan kichik bo‘lsin.');return;}setImportInfo('Fayl o‘qilmoqda…');try{let items:any[]=[];const ext=file.name.split('.').pop()?.toLowerCase();if(ext==='json'){const data=JSON.parse(await file.text());if(data.id&&data.wp&&data.settings){if(typeof data.firstName!=='string'||typeof data.lastName!=='string'||!Array.isArray(data.studied)||!Array.isArray(data.mistakes)||!Array.isArray(data.tests)||!data.notes||!Array.isArray(data.imports)||!Array.isArray(data.customQuestions)||!Array.isArray(data.bookmarks)||!Array.isArray(data.studyDays)||!data.grammar||typeof data.answered!=='number'||typeof data.correct!=='number'||!Number.isInteger(data.currentUnit))throw new Error('Progress zaxirasi tuzilishi noto‘g‘ri.');if(!confirm('Zaxiradagi profilni tiklaysizmi?'))return;await writeProfile(E.restoreDefaults(data));localStorage.setItem('essential-active',data.id);update(E.restoreDefaults(data));setImportInfo('Profil va natijalar tiklandi.');return;}items=Array.isArray(data)?data:data.vocabulary||[];}else if(ext==='csv'||ext==='txt'){const lines=(await file.text()).trim().split(/\r?\n/);items=lines.filter(l=>l.includes('\t')||l.includes(',')).map((l,i)=>{const [word,uzbekMeaning,meaning,example]=l.split(l.includes('\t')?'\t':',');return {word,uzbekMeaning,meaning,example};}).filter(x=>x.word.toLowerCase()!=='word');}else{const reader=new FileReader();const base64=await new Promise<string>((res,rej)=>{reader.onload=()=>res(String(reader.result).split(',')[1]);reader.onerror=rej;reader.readAsDataURL(file);});const res=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,mime:file.type,base64})});const data:any=await res.json();if(!res.ok)throw new Error(data.error);items=data.vocabulary||[];}
 if(!profile)return;const imported:Word[]=items.filter(x=>typeof x.word==='string'&&typeof x.uzbekMeaning==='string'&&typeof x.meaning==='string'&&typeof x.example==='string').map((x,i)=>({...x,id:x.id||`import-${Date.now()}-${i}`,unit:Number(x.unit)||profile.currentUnit,acceptedUzbekMeanings:x.acceptedUzbekMeanings||[x.uzbekMeaning],partOfSpeech:x.partOfSpeech||'',phonetic:x.phonetic||'',sourceType:'extra',verified:false,difficulty:1,page:0,sourceNote:file.name}));if(!imported.length)throw new Error('Import uchun word, uzbekMeaning, meaning, example maydonlari kerak. JSON yoki CSV shablonini yuklab oling.');update({...profile,imports:[...profile.imports,...imported]});setImportInfo(`${imported.length} ta so‘z tekshiruvga qo‘shildi. Tasdiqlashdan keyin mashqlarga chiqadi.`);}catch(e){setImportInfo(e instanceof Error?e.message:'Faylni o‘qib bo‘lmadi.');}}
 function Quiz(){if(!q)return null;return <section className="quiz-panel card"><div className="row between"><Source book={q.sourceType==='book'}/><span className="muted">{session?`${session.index+1} / ${session.questions.length}`:`${learnStep} / ${learnFormats.length}`} · {q.type}</span></div><Bar value={session?session.index/session.questions.length*100:learnStep/learnFormats.length*100}/>{q.audio&&<button className="audio-pill" onClick={()=>speak(q.audio!)}><Volume2 size={22}/> Eshitish</button>}<h2>{q.question}</h2>{q.speakingText&&<><blockquote className="speak-prompt">{q.speakingText}</blockquote><div className="row"><button type="button" className="btn primary large" disabled={micBusy||!!feedback} onClick={()=>{setAnswer('');record(q.speakingText,undefined,false,true);}}><Mic size={23}/> Ovoz bilan javob berish</button>{micBusy&&<button type="button" className="btn secondary" onClick={stopMic}>Tugatish</button>}</div><p className="muted">Nutq matnga solishtiriladi. Mikrofon ishlamasa pastdagi mikrofonsiz yo‘ldan davom eting.</p>{speechState&&<p role="status">{speechState}</p>}{answer&&<p>Siz aytdingiz: {answer}</p>}</>}{q.type==='order'&&<div className="word-tokens">{E.norm(q.question).split(' / ').map((token,i)=><button key={i} onClick={()=>setAnswer(a=>a+(a?' ':'')+token)} disabled={!!feedback}>{token}</button>)}</div>}<form onSubmit={e=>{e.preventDefault();submit();}}>{q.speakingText?null:q.options?<div className="answer-options">{q.options.map((o,i)=><button type="button" key={o} disabled={!!feedback} onClick={()=>setAnswer(o)} className={answer===o?'chosen':''}><span>{i+1}</span>{o}{answer===o&&<Check size={18}/>}</button>)}</div>:<input className="answer-input" aria-label="Javobingiz" autoComplete="off" autoCapitalize="none" placeholder="Javobingizni yozing…" value={answer} onChange={e=>setAnswer(e.target.value)} disabled={!!feedback}/>}
 {!feedback?<div className="quiz-actions"><button className="btn primary" disabled={!answer.trim()||!!(session?.deadline&&timer===0)} type="submit">Tekshirish</button><button type="button" className="btn ghost" onClick={()=>setHint(h=>h+1)} disabled={session?.mode==='mock'||session?.mode==='final'||session?.mode==='unit-test'||!!q.speakingText}>Yordam {hint>0?hint:''}</button>{q.speakingText&&!feedback&&<button type="button" className="btn ghost" onClick={()=>{stopMic();setAnswer('');setSpeechState('Mustaqil aytish — avtomatik ball berilmadi.');recognitionRef.current=null;setMicBusy(false);if(session){if(session.index+1>=session.questions.length)finishSession(session);else setSession({...session,index:session.index+1});}else setLearnStep(step=>step+1);}}>Mikrofonsiz qaytarib aytdim — ballsiz davom etish</button>}<Pick value={confidence} onChange={setConfidence} items={[["1","Ishonchim kam"],["3","Ishonchim komil"]]}/></div>:<div className={'feedback '+(feedback.ok?'good':'bad')} aria-live="polite"><strong>{feedback.ok?'To‘g‘ri! Yaxshi ishladingiz.':'Qayta eslab qolamiz.'}</strong>{!feedback.ok&&<p>To‘g‘ri javob: <b>{q.correctAnswer}</b></p>}<p>{q.explanation}</p><button type="button" className="btn primary" onClick={nextQuestion}>Davom etish</button></div>}
 {hint>0&&!feedback&&session?.mode!=='mock'&&session?.mode!=='final'&&session?.mode!=='unit-test'&&<p className="hint">{hint===1?`Birinchi belgi: ${q.correctAnswer[0]}.`:hint===2?`${q.correctAnswer.length} ta belgi. ${q.topic?grammarTopics.find(g=>g.id===q.topic)?.rule:'So‘zning o‘rganilgan ma’nosini eslang.'}`:hint===3?q.explanation:`Javob: ${q.correctAnswer}`}</p>}</form></section>;}
 if(!loaded)return <div className="welcome"><div className="brand-mark"><BookOpen/></div><h1>ESSENTIAL MASTERY</h1><p>O‘quv maydoningiz ochilmoqda…</p></div>;
 if(!profile)return <main className="welcome"><div className="welcome-brand"><div className="brand-mark"><BookOpen size={29}/></div><span>ESSENTIAL<br/><b>MASTERY</b></span></div><div className="welcome-card"><span className="eyebrow">SIZNING INGLIZ TILI MAYDONINGIZ</span><h1>O‘rganing.<br/><em>Esda qoldiring.</em></h1><p>600 so‘z. 30 Unit. Har kuni bir qadam oldinga.</p><form onSubmit={login}><label>Ismingiz<input value={fn} onChange={e=>setFn(e.target.value)} required autoComplete="given-name" placeholder="Ismingiz" maxLength={60}/></label><label>Familiyangiz<input value={ln} onChange={e=>setLn(e.target.value)} required autoComplete="family-name" placeholder="Familiyangiz" maxLength={60}/></label><button className="btn primary large" type="submit">Boshlash</button></form><small>Profilingiz va natijalar shu qurilmada saqlanadi.</small>{savingError&&<p className="error">{savingError}</p>}</div><div className="welcome-footer">4000 Essential English Words 1 · Paul Nation</div><Toaster/></main>;
 const unit=allUnits.find(u=>u.id===profile.currentUnit)!;const mastered=allWords.filter(w=>E.isMastered(profile.wp[w.id])).length;const activeMistakes=profile.mistakes.filter(m=>!m.resolved);
 const listWords=view==='weak'?weak:view==='weakpron'?allWords.filter(w=>profile.wp[w.id]?.seen&&!profile.wp[w.id]?.pronunciation.completed):allWords;
 const filteredWords=listWords.filter(w=>!search||E.norm(w.word+' '+w.uzbekMeaning+' '+w.unit).includes(E.norm(search))).slice(0,80);
 return <SidebarProvider><Sidebar className="app-sidebar"><SidebarHeader className="brand"><div className="brand-mark"><BookOpen size={22}/></div><div>ESSENTIAL<br/><b>MASTERY</b></div></SidebarHeader><SidebarContent>{navGroups.map(g=><SidebarGroup key={g.label}><SidebarGroupLabel>{g.label}</SidebarGroupLabel><SidebarMenu>{g.items.map(([id,name,Icon]:any)=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id||view==='unit'&&id==='units'} onClick={()=>id==='learn'?startLearning():go(id)}><Icon size={18}/><span>{label(id,name)}</span>{id==='review'&&due.length>0&&<span className="nav-count">{due.length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup>)}</SidebarContent><SidebarFooter><button className="side-setting" onClick={()=>go('settings')}><Settings size={17}/> {label('settings','Sozlamalar')}</button><button className="side-profile" onClick={()=>go('profile')}><span className="avatar">{profile.firstName[0]}{profile.lastName[0]}</span><span><b>{profile.firstName}</b><small>Shaxsiy o‘quv maydoni</small></span><MoreHorizontal size={18}/></button></SidebarFooter></Sidebar>
 <div className="workspace"><header className="topbar"><div className="row"><SidebarTrigger/><span className="breadcrumb">O‘quv maydoni <ChevronRight size={14}/> <b>{label(view,String(title))}</b></span></div><div className="top-actions"><span className="book-edition">BOOK 01</span><button aria-label="Rang rejimini almashtirish" className="icon-btn" onClick={()=>update({...profile,settings:{...profile.settings,theme:profile.settings.theme==='dark'?'light':'dark'}})}>{profile.settings.theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button><button className="avatar small" onClick={()=>go('profile')}>{profile.firstName[0]}</button></div></header>
 <main className="main-content">{savingError&&<div className="save-error">{savingError}<button onClick={()=>download('essential-progress.json',JSON.stringify(profile,null,2))}>Zaxira olish</button></div>}
 <div className="page-heading"><div><span className="eyebrow">{view==='home'?'HAR KUNI BIR QADAM':`ESSENTIAL MASTERY / ${englishLabels[view]||'UNIT '+profile.currentUnit}`}</span><h1>{view==='home'?<>Salom, {profile.firstName}<span className="greeting-dot">.</span></>:view==='unit'?`Unit ${unit.id}`:label(view,String(title))}</h1><p>{view==='home'?'Bugun o‘rganganingiz ertaga ham yodingizda qolsin.':view==='unit'?unit.title:view==='learn'?'Eshiting, qaytarib ayting va har ikki yo‘nalishda eslab qoling.':view==='review'?'Avvalgi barcha Unitlar takrorlash ro‘yxatida qoladi.':'4000 Essential English Words 1'}</p></div>{!session&&<label className="search-box"><Search size={18}/><input aria-label="So‘z yoki mavzu qidirish" placeholder="So‘z, Unit yoki mavzu…" value={search} onChange={e=>{setSearch(e.target.value);if(view==='home')setView('vocabulary');}}/><kbd>⌕</kbd></label>}</div>
 {session?session.done?<section className="card result"><div className="result-mark"><Trophy size={36}/></div><span className="eyebrow">MASHQ YAKUNLANDI</span>{isOdina && session.mode === 'unit-test' && (
  <div style={{ margin: '18px 0 24px' }}>
    <p style={{ color: '#d6a6c8', fontSize: 20, fontWeight: 600 }}>
      Omad senga, Odina (A.O)✨
    </p>
    <small style={{
      display: 'block',
      marginTop: 6,
      fontSize: 11,
      color: '#d6a6c8',
      opacity: 0.45
    }}>
      (A.O)
      (Abdumalik)
      (Odina)
      (Namozova)
      (Abdug'aniyev)
    </small>
  </div>
)}<h2>{session.correct} / {session.answers.length}</h2>{session.mode==='unit-test'&&<p>Unit {profile.currentUnit}: {session.questions.filter(q=>q.unit===profile.currentUnit).length} savol · Oldingi Unitlar: {session.questions.filter(q=>q.unit!==profile.currentUnit).length} savol</p>}<p>{session.answers.length?Math.round(session.correct/session.answers.length*100):0}% aniqlik · {session.answers.filter(a=>!a.ok).length} ta xato</p>{session.mode.startsWith('rapid')&&<p>Eng yaxshi ketma-ketlik: {session.answers.reduce((a,x)=>x.ok?{run:a.run+1,best:Math.max(a.best,a.run+1)}:{...a,run:0},{run:0,best:0}).best}</p>}<div className="result-grid"><Stat icon={CheckCircle2} value={session.correct} label="To‘g‘ri javob"/><Stat icon={Target} value={`${E.unitMastery(profile,profile.currentUnit,allWords)}%`} label="Unit mastery"/></div>{session.mode==='perfect'&&<p>{E.unitMastery(profile,profile.currentUnit,allWords)>=90&&!activeMistakes.length?'Unit mustahkamlandi.':'Mastery uchun hali mashq kerak. 90% aniqlik, barcha talaffuz bosqichlari va xatolarni tuzatish talab qilinadi.'}</p>}{session.nextUnit?<button className="btn primary" onClick={()=>{const id=session.nextUnit!;update({...profile,currentUnit:id,studied:Array.from(new Set([...profile.studied,id]))});setWordIndex(0);setSession(null);setView('unit');}}>Unit {session.nextUnit}ni ochish</button>:<div className="row center"><button className="btn primary" onClick={()=>startSession(session.mode,Number(mockCount),'mixed')}>Yana mashq</button><button className="btn secondary" onClick={()=>go('mistakes')}>Xatolarni ko‘rish</button></div>}{(session.mode==='mock'||session.mode==='final'||session.mode==='unit-test')&&<div className="test-answers">{session.answers.map((a,i)=><div key={i}><span>{a.ok?'✓':'×'} {a.q.question}</span><small>Siz: {a.answer} · To‘g‘ri: {a.q.correctAnswer}</small></div>)}</div>}</section>:<><div className="session-header"><button className="btn ghost" onClick={()=>{if(confirm('Mashqdan chiqasizmi? Berilgan javoblar saqlangan.'))go('practice');}}><X size={16}/> Chiqish</button><span>{session.mode==='book'?'Kitob mashqlari':session.mode==='perfect'?'MASTER UNTIL PERFECT':session.mode==='unit-test'?`Unit ${profile.currentUnit} yakuniy testi`:session.mode==='previous'?'Previous Words Check':session.mode.startsWith('rapid')?`Rapid Fire · ${timer}s`:'Mashq'} · <b>{session.correct} to‘g‘ri</b></span></div>{Quiz()}</>:
 view==='home'?<><div className="dashboard-grid"><section className="continue-card"><div className="row between"><span className="pill"><span/> DAVOM ETAMIZ</span><span className="unit-tag">UNIT {String(unit.id).padStart(2,'0')}</span></div><h2>{unit.title}</h2><p>Kitob so‘zlari, talaffuz va amaliy mashqlar</p><div className="continue-footer"><div><span className="muted-light">Unit mastery</span><strong>{E.unitMastery(profile,unit.id,allWords)}%</strong><Bar value={E.unitMastery(profile,unit.id,allWords)}/></div><button className="btn white" onClick={()=>startLearning()}><Play size={16} fill="currentColor"/> O‘rganishni davom ettirish</button></div><div className="big-unit" aria-hidden="true">{String(unit.id).padStart(2,'0')}</div></section><section className="daily-card card"><div className="row between"><h3>Kunlik maqsad</h3><Clock size={18}/></div><div className="goal-ring" style={{background:`conic-gradient(var(--primary) ${Math.min(100,(profile.daySeconds?.[E.dateKey()]||0)/60/profile.settings.goal*100)}%, var(--border) 0)`}}><div><b>{Math.floor((profile.daySeconds?.[E.dateKey()]||0)/60)}</b><span>/ {profile.settings.goal} daqiqa</span></div></div><div className="row between"><span><Flame size={17}/> {E.streak(profile)} kunlik davomiylik</span><button className="text-btn" onClick={()=>go('settings')}>O‘zgartirish</button></div></section></div>
 <div className="stats-grid"><Stat icon={BookOpen} value={mastered} label="Mustahkam so‘zlar"/><Stat icon={Target} value={`${E.overall(profile,allWords)}%`} label="Umumiy mastery"/><Stat icon={CheckCircle2} value={`${E.accuracy(profile)}%`} label="Javoblar aniqligi"/><Stat icon={BarChart3} value={profile.answered} label="Berilgan javoblar"/></div>
 <div className="section-heading"><h2>Bugungi o‘quv reja</h2><span className="muted">{profile.settings.goal} daqiqa · shaxsiy reja</span></div><div className="plan-grid">{[['review',RotateCcw,'Aqlli takrorlash',`${due.length} ta vaqti kelgan so‘z`,'review'],['pronunciation',Mic,'Talaffuz mashqi','Eshiting va qaytarib ayting','pronunciation'],['grammar',FileText,'Grammatika','Qoida, misol va mini mashq','grammar']].map(([id,Icon,t,d,dest]:any,i)=><button className="plan-card card" key={id} onClick={()=>go(dest)}><span className={'plan-icon tone-'+i}><Icon size={23}/></span><div><h3>{t}</h3><p>{d}</p><small>{Math.max(2,Math.round(profile.settings.goal/6))} daqiqa</small></div><ChevronRight size={18}/></button>)}</div>
 <div className="lower-grid"><section className="card word-preview"><div className="row between"><h3>Hozirgi so‘z</h3><Source book/></div><h2>{activeWord?.word}</h2><p>{activeWord?.uzbekMeaning} <span className="muted">· {activeWord?.partOfSpeech}</span></p><div className="row between"><span className="muted">Unit {profile.currentUnit} · {levelNames[E.level(profile.wp[activeWord?.id||''])]}</span><button className="icon-btn purple" onClick={()=>activeWord&&speak(activeWord.word)} disabled={!activeWord} aria-label="So‘zni eshitish"><Volume2 size={21}/></button></div></section><section className="card review-preview"><div className="row between"><h3>Eslab qolishni mustahkamlang</h3><Bookmark size={18}/></div><p>Eski so‘zlar yo‘qolmaydi. Zaif so‘zlar tezroq, mustahkam so‘zlar uzoqroq intervalda qaytadi.</p><div className="row"><button className="btn secondary" onClick={()=>go('weak')}>Zaif so‘zlar <b>{weak.length}</b></button><button className="btn ghost" onClick={()=>startSession('previous',10)}>Oldingi so‘zlar</button></div></section></div></>:
 view==='units'?<><div className="book-summary card"><div className="book-icon"><BookOpen size={29}/></div><div><h3>4000 Essential English Words 1</h3><p>Paul Nation · 2009 · 30 Unit · 600 asosiy so‘z</p></div><span className="source book">Yuklangan PDF asosida</span></div><div className="unit-grid">{allUnits.filter(u=>!search||E.norm(u.id+' '+u.title).includes(E.norm(search))).map(u=><button key={u.id} className={'unit-card card '+(u.id===profile.currentUnit?'current':'')} onClick={()=>openUnit(u.id)}><div className="row between"><span className="unit-number">{String(u.id).padStart(2,'0')}</span>{u.id===profile.currentUnit?<span className="mini-badge">Hozirgi Unit</span>:profile.studied.includes(u.id)?<span className="muted">O‘rganilmoqda</span>:<span className="muted">{allWords.filter(w=>w.unit===u.id).length} so‘z</span>}</div><h3>{u.title}</h3><Bar value={E.unitMastery(profile,u.id,allWords)}/><div className="row between"><span>{E.unitMastery(profile,u.id,allWords)}% mastery</span><span className="muted">p. {u.page}</span></div></button>)}</div></>:
 view==='unit'?<><section className="card unit-detail"><div className="row between"><Source book/><button className="icon-btn" aria-label="Unitni saqlash" onClick={()=>bookmark('unit-'+unit.id)}><Bookmark fill={profile.bookmarks.includes('unit-'+unit.id)?'currentColor':'none'} size={20}/></button></div><h2>{unit.title}</h2><p>{currentWords.length} so‘z · Har so‘zga 4–5 ta oson gap · Unit oxirida test. Testda oldingi o‘rganilgan Unitlar ham qaytadi.</p><Bar value={E.unitMastery(profile,unit.id,allWords)}/><div className="row"><button className="btn primary" onClick={()=>startLearning()}>So‘zlarni o‘rganish</button><button className="btn secondary" onClick={()=>startSession('book')}>Kitob mashqlari</button><button className="btn ghost" onClick={()=>startSession('current')}>Extra Practice</button><button className="btn primary" onClick={()=>startUnitTest()}>Unit yakuniy testi</button></div></section><Tabs defaultValue="words"><TabsList><TabsTrigger value="words">Book Vocabulary</TabsTrigger><TabsTrigger value="skills">Ko‘nikmalar</TabsTrigger><TabsTrigger value="notes">Qaydlar</TabsTrigger></TabsList><TabsContent value="words"><div className="vocab-grid">{currentWords.map(w=><WordCard key={w.id} w={w}/>)}</div></TabsContent><TabsContent value="skills"><div className="plan-grid">{[['pronunciation','Talaffuz',Mic],['listening','Tinglash',Headphones],['grammar','Extra Grammar',FileText]].map(([id,n,Icon]:any)=><button className="card plan-card" key={id} onClick={()=>go(id)}><Icon/><h3>{n}</h3></button>)}</div><div className="card dimension-grid">{E.dimensions.map(d=><div key={d}><span>{dimNames[d]}</span><b>{Math.round(currentWords.reduce((a,w)=>a+E.dimensionScore(profile.wp[w.id],d),0)/Math.max(1,currentWords.length))}%</b></div>)}</div></TabsContent><TabsContent value="notes"><div className="card"><label className="form-label">Unit {unit.id} uchun shaxsiy qayd<textarea rows={8} value={profile.notes[unit.id]||''} onChange={e=>update({...profile,notes:{...profile.notes,[unit.id]:e.target.value}})} placeholder="Qoidalar, misollar, eslab qolish usullari…"/></label><small className="muted">Avtomatik saqlanadi.</small></div></TabsContent></Tabs></>:
 view==='learn'?!activeWord?<Empty title="Bu Unitda so‘z yo‘q" text="Boshqa Unitni tanlang." action={<button className="btn primary" onClick={()=>go('units')}>Boshqa Unitni tanlash</button>}/>:<>{learnStep===0?<section className="card learn-card"><div className="row between"><Source book/><Pick value={String(wordIndex)} onChange={v=>{setWordIndex(Number(v));resetLearn();}} items={currentWords.filter(w=>w.verified).map((w,i)=>[String(i),w.word])}/></div><div className="learning-steps"><span className="active">01 Eshitish & aytish</span><span>02 Ma’no</span><span>03 Yozish</span><span>04 Kontekst</span></div><div className="learn-word"><span className="muted">UNIT {unit.id} · {wordIndex+1} / {currentWords.length}</span><h2>{activeWord.word}</h2><span className="word-pos">{activeWord.partOfSpeech}</span><div className="pron-buttons"><button className="btn primary large" onClick={()=>speak(activeWord.word)}><Volume2 size={23}/> Eshitish</button><button className="btn secondary large" disabled={micBusy} onClick={()=>record(activeWord.word,activeWord)}><Mic size={23}/> Aytib ko‘rish</button></div><small>Approximate pronunciation check · nutqni matnga solishtirish</small>{speechState&&<div className="speech-feedback" aria-live="polite"><b>{speechState}</b>{detected&&<p>Expected: {activeWord.word}<br/>Detected: {detected}</p>}</div>}{speechState&&!detected&&speechState!=='Tinglayapman…'&&<button className="text-btn" onClick={fallback}>O‘zim qaytarib aytdim — mikrofonsiz davom etish</button>}</div><div className="meaning-block"><div><span className="eyebrow">O‘ZBEKCHA MA’NO</span><h3>{activeWord.uzbekMeaning}</h3><p>{activeWord.meaning}</p></div><div className="example"><span className="eyebrow">KONTEKST</span><ol className="simple-examples">{simpleExamples.map((ex,i)=><li key={ex}><span>{E.writtenExamples(activeWord)[i]}</span><button className="icon-btn" onClick={()=>speak(ex)} aria-label={`Misol ${i+1}ni eshitish`}><Volume2 size={18}/></button></li>)}</ol><small>Har mashqda boshqa gap: listening qisqa, writing uzunroq. Bir gap bir darsda qayta berilmaydi.</small></div></div><div className="row between"><span className="muted">{listened?'✓ Eshitildi':'Eshitish'} · {attempted?'✓ Aytilgan':'Aytib ko‘rish'}</span><button className="btn primary" onClick={learnerStart}>Ma’noni tekshirish</button></div></section> :Quiz()}</>:
 ['vocabulary','weak','weakpron'].includes(view)?<><div className="row between list-toolbar"><p className="muted">{listWords.length} ta so‘z · {filteredWords.length} tasi ko‘rsatilmoqda</p><div className="row"><button className="btn secondary" onClick={()=>go(view==='weak'?'vocabulary':'weak')}>{view==='weak'?'Barcha so‘zlar':'Zaif so‘zlar'}</button>{view==='weak'&&<button className="btn primary" onClick={()=>startSession('weak')}>Practice Weakest First</button>}</div></div>{filteredWords.length?<div className="vocab-grid">{filteredWords.map(w=><WordCard key={w.id} w={w}/>)}</div>:<Empty title="Hali so‘z yo‘q" text="Avval yangi so‘zlarni o‘rganing. Qidiruv bo‘lsa, boshqa so‘z kiriting." action={<button className="btn primary" onClick={()=>startLearning()}>O‘rganish</button>}/>}</>:
 view==='grammar'?<><div className="grammar-layout"><div className="grammar-list card">{grammarTopics.filter(t=>!search||E.norm(t.name+' '+t.rule).includes(E.norm(search))).map(t=><button key={t.id} className={grammarId===t.id?'active':''} onClick={()=>setGrammarId(t.id)}><FileText size={17}/>{t.name}<span>{profile.grammar[t.id]?Math.round(profile.grammar[t.id].correct/profile.grammar[t.id].total*100):0}%</span></button>)}</div><section className="card grammar-rule"><Source/><h2>{grammarTopics.find(t=>t.id===grammarId)!.name}</h2><p className="rule-text">{grammarTopics.find(t=>t.id===grammarId)!.rule}</p><div className="grammar-examples">{[['positive','Positive'],['negative','Negative'],['question','Question']].map(([k,n])=><div key={k}><span>{n}</span><p>{(grammarTopics.find(t=>t.id===grammarId) as any)[k]}</p></div>)}</div><div className="common-mistake"><b>Ko‘p uchraydigan xato</b><p>{grammarTopics.find(t=>t.id===grammarId)!.mistake}</p></div><div className="row"><button className="btn primary" onClick={()=>startSession('grammar')}>Mini mashq</button><button className="btn secondary" onClick={()=>speak(grammarTopics.find(t=>t.id===grammarId)!.speaking)}><Volume2 size={17}/> Misolni eshitish</button><button className="icon-btn" aria-label="Qoidani saqlash" onClick={()=>bookmark('grammar-'+grammarId)}><Bookmark fill={profile.bookmarks.includes('grammar-'+grammarId)?'currentColor':'none'}/></button></div></section></div></>:
 view==='pronunciation'?!activeWord?<Empty title="Bu Unitda so‘z yo‘q" text="Talaffuz uchun tasdiqlangan so‘z qo‘shing."/>:<><section className="card pronunciation-card"><Source book/><h2>Eshiting. Qaytarib ayting.</h2><Pick value={String(wordIndex)} onChange={v=>{setWordIndex(Number(v));setDetected('');setSpeechState('');}} items={currentWords.map((w,i)=>[String(i),w.word])}/><h3>{activeWord.word}</h3><Pick value={String(exampleIndex%simpleExamples.length)} onChange={v=>{setExampleIndex(Number(v));setSpeechState('');setDetected('');}} items={simpleExamples.map((ex,i)=>[String(i),`Gap ${i+1}`])}/><p>{simpleExamples[exampleIndex%simpleExamples.length]}</p><div className="pron-buttons"><button className="btn primary large" onClick={()=>speak(activeWord.word)}><Volume2/> So‘zni eshitish</button><button className="btn secondary large" disabled={micBusy} onClick={()=>record(activeWord.word,activeWord)}><Mic/> So‘zni aytish</button><button className="btn secondary" onClick={()=>{speak(simpleExamples[exampleIndex%simpleExamples.length]);}}><Headphones/> Gapni eshitish</button><button className="btn secondary" onClick={()=>record(simpleExamples[exampleIndex%simpleExamples.length],activeWord)}><Mic/> Gapni qaytarish</button></div><p className="muted">Approximate pronunciation check. Professional fonetik baholash emas.</p>{speechState&&<div className="speech-feedback"><strong>{speechState}</strong>{detected&&<p>Detected: {detected}</p>}</div>}<button className="text-btn" onClick={()=>go('weakpron')}>Zaif talaffuz so‘zlarini ko‘rish</button></section></>:
 view==='listening'?<><section className="card"><h3>Elementary listening</h3><p>Qisqa gaplar, sekin ovoz. Har audioni xohlagancha qayta eshiting.</p><Pick value={String(profile.settings.audioRate)} onChange={v=>update({...profile,settings:{...profile.settings,audioRate:Number(v)}})} items={[["0.5","Juda sekin"],["0.65","Sekin (Elementary)"],["0.8","O‘rtacha"],["1","Oddiy"]]}/></section><div className="practice-grid">{[['speak-word','So‘zni o‘qish → ovoz bilan aytish',Mic],['speak-sentence','Qisqa gapni o‘qish → ovoz bilan aytish',Mic],['listening','Eshitish → so‘zni yozish',Headphones],['spelling','Audio → so‘zni yozish',Keyboard],['dictation','Gap diktanti',PenLine]].map(([f,n,Icon]:any)=><button className="card mode-card" key={f} onClick={()=>startSession('current',20,f)}><span className="plan-icon"><Icon size={26}/></span><h3>{n}</h3><p>Hozirgi va oldingi o‘rganilgan Unitlar</p><span className="text-btn">Boshlash</span></button>)}</div></>:
 view==='speaking'||view==='writing'?<section className="card writing-card"><Source/><h2>{view==='speaking'?'O‘z fikringizni ayting':'Fikringizni inglizcha yozing'}</h2><Pick value={writingTopic} onChange={v=>{setWritingTopic(v);setWritingFeedback('');}} items={['My family','My daily routine','My school','My plans','A past event','Short email','Short opinion','Description'].map(s=>[s,s])}/><p className="writing-prompt">{writingTopic==='My family'?'Tell me about your family.':writingTopic==='My daily routine'?'Describe your daily routine.':writingTopic==='A past event'?'What did you do yesterday?':`Write or speak about: ${writingTopic}.`}</p>{view==='speaking'&&<div className="row"><button className="btn primary large" disabled={micBusy} onClick={()=>record(undefined,undefined,true)}><Mic size={24}/> Gapirish</button><button className="btn secondary" onClick={stopMic}>To‘xtatish</button></div>}<textarea rows={8} aria-label="Inglizcha javobingiz" value={writing} onChange={e=>setWriting(e.target.value)} placeholder="Inglizcha javobingiz…"/><div className="row between"><span className="muted">{writing.trim()?writing.trim().split(/\s+/).length:0} ta so‘z {view==='speaking'&&speechState}</span><button className="btn primary" disabled={!writing.trim()||aiBusy} onClick={checkWriting}>{aiBusy?'Tekshirilmoqda…':'Tekshirish'}</button></div>{writingFeedback&&<div className="writing-feedback" aria-live="polite">{writingFeedback}</div>}</section>:
 view==='practice'?<><div className="row list-toolbar"><Pick value={format} onChange={setFormat} items={[["mixed","Aralash savollar"],["en-uz","English → Uzbek"],["uz-en","Uzbek → English"],["choice","Variantli savol"],["meaning","English meaning"],["context","Kontekst"],["true-false","True / False"]]}/><button className="btn primary" onClick={()=>startSession('current')}>Hozirgi Unit</button></div><div className="practice-grid">{[['book','Kitob mashqlari',BookOpen,'Kitobdagi vocabulary va mashqlar'],['random','Random Practice',LayoutGrid,'Faqat o‘rganilgan so‘zlar'],['weak','Zaif so‘zlar',Target,'Eng zaif so‘zlardan boshlash'],['previous','Previous Words Check',RotateCcw,'Barcha avvalgi Unitlardan'],['perfect','Master Until Perfect',Flame,'90% mastery sari mashq'],['rapid30','Rapid Fire · 30s',Clock,'Tezkor so‘z mashqi'],['rapid60','Rapid Fire · 60s',Clock,'Bir daqiqalik sinov'],['mistakes','Xatolardan mashq',AlertCircle,'Tuzatilmagan xatolar']].map(([mode,n,Icon,d]:any)=><button className="card mode-card" key={mode} onClick={()=>startSession(mode,mode.startsWith('rapid')?100:20)}><span className="plan-icon"><Icon size={25}/></span><h3>{n}</h3><p>{d}</p><span className="text-btn">Boshlash</span></button>)}</div></>:
 view==='review'?<><div className="review-banner card"><div><h2>{due.length} ta so‘z takrorlashga tayyor</h2><p>Interval javoblaringiz, ishonchingiz va xatolaringizga qarab o‘zgaradi.</p></div><button className="btn primary" disabled={!due.length} onClick={()=>startSession('due')}>Bugungi takrorlash</button></div><div className="plan-grid"><button className="card plan-card" onClick={()=>startSession('previous',20)}><RotateCcw/><div><h3>Avvalgi so‘zlar</h3><p>{old.length} ta o‘rganilgan so‘z</p></div></button><button className="card plan-card" onClick={()=>go('weak')}><Target/><div><h3>Zaif so‘zlar</h3><p>{weak.length} ta mustahkamlash kerak</p></div></button><button className="card plan-card" onClick={()=>go('mistakes')}><AlertCircle/><div><h3>Xatolar</h3><p>{activeMistakes.length} ta tuzatilmagan</p></div></button></div>{due.length?<div className="vocab-grid">{due.slice(0,40).map(w=><WordCard key={w.id} w={w}/>)}</div>:<Empty title="Hozircha takrorlash yo‘q" text="Yangi so‘zlarni o‘rganing. Ular keyingi takrorlashga avtomatik qo‘shiladi." action={<button className="btn primary" onClick={()=>startLearning()}>Yangi so‘zlar</button>}/>}</>:
 view==='mistakes'?<>{profile.mistakes.length?<><div className="row between list-toolbar"><span>{activeMistakes.length} ta faol · {profile.mistakes.length-activeMistakes.length} ta tuzatilgan</span><button className="btn primary" onClick={()=>startSession('mistakes')}>Xatolarni mashq qilish</button></div><div className="mistake-list">{profile.mistakes.map(m=><article className="card mistake-card" key={m.id}><div className="row between"><span className={'mini-badge '+(m.resolved?'resolved':'')}>{m.resolved?'Tuzatildi':m.type}</span><span className="muted">Unit {m.unit} · {m.times} marta</span></div><h3>{m.question}</h3><div className="mistake-answers"><p>Siz: <span>{m.answer}</span></p><p>To‘g‘ri: <b>{m.correct}</b></p></div><p>{m.explanation}</p><small className="muted">Oxirgi tekshiruv: {new Date(m.lastReviewed).toLocaleDateString('uz-UZ')}</small></article>)}</div></>:<Empty title="Hali xatolar yo‘q" text="Mashqlardagi xatolar shu yerda saqlanadi. Xato qilish o‘rganishning bir qismi." action={<button className="btn primary" onClick={()=>go('practice')}>Mashq qilish</button>}/>}</>:
 view==='mock'?<section className="card mock-card"><div className="result-mark"><CheckCircle2 size={38}/></div><Source/><h2>Bilimingizni sinab ko‘ring</h2><p>Faqat o‘rganilgan so‘zlar. Javoblar test oxirida ko‘rsatiladi.</p><Pick value={mockCount} onChange={setMockCount} items={[["20","20 ta savol"],["50","50 ta savol"],["100","100 ta savol"]]}/><button className="btn primary large" onClick={()=>startSession('mock',Number(mockCount),'mixed')}>Testni boshlash</button>{profile.tests.length>0&&<div className="test-history">{profile.tests.slice(-5).reverse().map((t,i)=><div className="row between" key={i}><span>{new Date(t.at).toLocaleDateString('uz-UZ')}</span><b>{t.score}/{t.total} · {Math.round(t.score/t.total*100)}%</b></div>)}</div>}</section>:
 view==='progress'||view==='mastery'?<><div className="stats-grid"><Stat icon={Trophy} value={`${E.overall(profile,allWords)}%`} label="Umumiy mastery"/><Stat icon={BookOpen} value={`${allUnits.filter(u=>E.unitMastery(profile,u.id,allWords)>=90).length}/30`} label="Mustahkam Unitlar"/><Stat icon={Languages} value={`${mastered}/600`} label="Mastered so‘zlar"/><Stat icon={Clock} value={`${Math.floor(profile.studySeconds/60)} min`} label="O‘qish vaqti"/></div>{view==='mastery'&&<div className="card mastery-banner"><Trophy size={40}/><div><h2>{E.bookMastered(profile,allWords)?'🏆 BOOK MASTERED':'Haqiqiy bilim — uzoq muddatli xotira'}</h2><p>Har olti ko‘nikma kamida 3 alohida kunda tekshiriladi. Bitta to‘g‘ri javob yetarli emas.</p><p>30 Unit ≥ 90% · talaffuz va tinglash · yakuniy test ≥ 90% · barcha xatolar tuzatilgan · takrorlash bajarilgan.</p></div><button className="btn primary" onClick={()=>startSession('final',100)}>Yakuniy test</button></div>}<section className="card"><h3>Ko‘nikmalar bo‘yicha</h3><div className="dimension-grid">{E.dimensions.map(d=><div key={d}><span>{dimNames[d]}</span><b>{Math.round(allWords.reduce((s,w)=>s+E.dimensionScore(profile.wp[w.id],d),0)/allWords.length)}%</b><Bar value={allWords.reduce((s,w)=>s+E.dimensionScore(profile.wp[w.id],d),0)/allWords.length}/></div>)}</div></section><div className="card progress-list"><h3>Unitlar bo‘yicha natijalar</h3>{allUnits.map(u=><button key={u.id} className="progress-row" onClick={()=>openUnit(u.id)}><b>{String(u.id).padStart(2,'0')}</b><span>{u.title}</span><Bar value={E.unitMastery(profile,u.id,allWords)}/><strong>{E.unitMastery(profile,u.id,allWords)}%</strong></button>)}</div></>:
 view==='tutor'?<section className="card tutor-card"><div className="tutor-heading"><span className="plan-icon"><Sparkles size={24}/></span><div><h3>Shaxsiy tutor</h3><p>Kitob mashqlari va Gemini AI Tutor</p></div><Source/></div><div className="tutor-chips">{['Unit '+profile.currentUnit+'dan savol ber','O‘zbekchadan English so‘ra','Grammar tushuntir','Weak words’dan so‘ra'].map(t=><button key={t} onClick={()=>setTutorText(t)}>{t}</button>)}</div><div className="chat-messages" aria-live="polite">{messages.map((m,i)=><div key={i} className={'chat-message '+m.role}><span>{m.role==='assistant'?'EM':'Siz'}</span><p>{m.text}</p></div>)}{aiBusy&&<p>Javob tayyorlanmoqda…</p>}</div><form className="chat-input" onSubmit={e=>{e.preventDefault();tutorSend();}}><input value={tutorText} onChange={e=>setTutorText(e.target.value)} placeholder="Savol yoki javobingiz…" aria-label="Tutor xabari"/><button className="btn primary" disabled={aiBusy||!tutorText.trim()}>Yuborish</button></form></section>:
 view==='profile'?<><section className="card profile-card"><span className="avatar large">{profile.firstName[0]}{profile.lastName[0]}</span><div><h2>{profile.firstName} {profile.lastName}</h2><p>Unit {profile.currentUnit} · {profile.studied.length} ta ochilgan Unit</p></div><button className="btn secondary" onClick={()=>go('settings')}>Sozlamalar</button></section><div className="stats-grid"><Stat icon={Flame} value={`${E.streak(profile)} kun`} label="Davomiylik"/><Stat icon={CheckCircle2} value={profile.answered} label="Javoblar"/><Stat icon={Bookmark} value={profile.bookmarks.length} label="Saqlanganlar"/><Stat icon={Clock} value={`${Math.floor(profile.studySeconds/60)} min`} label="O‘qish vaqti"/></div><section className="card"><h3>Saqlangan so‘zlar va qoidalar</h3>{profile.bookmarks.length?<div className="saved-list">{profile.bookmarks.map(id=>{const w=allWords.find(w=>w.id===id);return <button key={id} onClick={()=>{if(w)setSelectedWord(w);else if(id.startsWith('unit-'))openUnit(Number(id.slice(5)));else if(id.startsWith('grammar-')){setGrammarId(id.slice(8));go('grammar');}}}><Bookmark size={17}/>{w?`${w.word} — ${w.uzbekMeaning}`:id}</button>;})}</div>:<p className="muted">Bookmark belgisi orqali so‘z va qoidalarni saqlang.</p>}</section></>:
 view==='settings'?<section className="card settings-card"><h2>O‘quv maydoningiz</h2><div className="setting-row"><div><h3>Rang rejimi</h3><p>O‘zingizga qulay ko‘rinishni tanlang.</p></div><Pick value={profile.settings.theme} onChange={v=>update({...profile,settings:{...profile.settings,theme:v}})} items={[["light","Light"],["dark","Dark"],["system","System"]]}/></div><div className="setting-row"><div><h3>Interfeys tili</h3><p>O‘zbekcha yoki English navigatsiya.</p></div><Pick value={profile.settings.language} onChange={v=>update({...profile,settings:{...profile.settings,language:v}})} items={[["uz","O‘zbekcha"],["en","English"]]}/></div><div className="setting-row"><div><h3>Talaffuz majburiy</h3><p>Yangi so‘zdan oldin eshitish va aytib ko‘rish.</p></div><Switch checked={profile.settings.required} onCheckedChange={v=>update({...profile,settings:{...profile.settings,required:v}})}/></div><div className="setting-row"><div><h3>Ovoz</h3><p>So‘zlar va gaplarni ovozli o‘qish.</p></div><Switch checked={profile.settings.sound} onCheckedChange={v=>update({...profile,settings:{...profile.settings,sound:v,required:v?profile.settings.required:false}})}/></div><div className="setting-row"><div><h3>Kunlik maqsad</h3><p>O‘qish uchun ajratilgan vaqt.</p></div><Pick value={String(profile.settings.goal)} onChange={v=>update({...profile,settings:{...profile.settings,goal:Number(v)}})} items={['10','20','30','60'].map(s=>[s,s+' daqiqa'])}/></div><div className="settings-actions"><button className="btn secondary" onClick={()=>download('essential-progress.json',JSON.stringify(profile,null,2))}><Download size={17}/> Progress zaxirasi</button><label className="btn secondary"><Upload size={17}/> Zaxirani tiklash<input type="file" accept=".json" hidden onChange={e=>{if(e.target.files?.[0])importFile(e.target.files[0]);}}/></label><button className="btn secondary" onClick={async()=>{await writeProfile(profile);localStorage.removeItem('essential-active');setProfile(null);setFn('');setLn('');setSession(null);setView('home');}}><LogOut size={17}/> Foydalanuvchini almashtirish</button><button className="btn danger" onClick={()=>setResetOpen(true)}><Trash2 size={17}/> Progressni tozalash</button></div><p className="muted">Natijalar shu brauzerda saqlanadi. Boshqa qurilmaga o‘tkazish uchun zaxira faylidan foydalaning.</p>{importInfo&&<p>{importInfo}</p>}</section>:
 null}
 <footer className="page-footer"><span>ESSENTIAL MASTERY</span><span>Learn it. Use it. Remember it.</span><span>Book 01 · 30 Units</span></footer>
 {(['learn','pronunciation','speaking','weakpron','settings'].includes(view)||!!q?.speakingText)&&microphoneTools()}</main><nav className="mobile-nav">{[['home',Home],['learn',GraduationCap],['practice',LayoutGrid],['review',RotateCcw],['profile',Languages]].map(([id,Icon]:any)=><button key={id} className={view===id?'active':''} onClick={()=>id==='learn'?startLearning():go(id)}><Icon size={20}/><span>{englishLabels[id]}</span></button>)}</nav></div>
 <Dialog open={!!selectedWord} onOpenChange={v=>{if(!v)setSelectedWord(null);}}><DialogContent className="word-dialog"><DialogHeader><DialogTitle>{selectedWord?.word}</DialogTitle><DialogDescription>Unit {selectedWord?.unit} · Essential vocabulary</DialogDescription></DialogHeader>{selectedWord&&<><Source book={selectedWord.sourceType==='book'}/><h3>{selectedWord.uzbekMeaning}</h3><p>{selectedWord.meaning}</p><ol className="simple-examples">{E.writtenExamples(selectedWord).map((ex,i)=><li key={ex}><span>{ex}</span><button className="icon-btn" onClick={()=>speak(ex)} aria-label={`Misol ${i+1}ni eshitish`}><Volume2 size={18}/></button></li>)}</ol><details><summary>Kitobdagi asl misol</summary><p>{selectedWord.example}</p></details><div className="row"><button className="btn secondary" onClick={()=>speak(selectedWord.word)}><Volume2/> Eshitish</button><button className="btn primary" onClick={()=>{startLearning(selectedWord);setSelectedWord(null);}}>O‘rganish</button><button className="icon-btn" aria-label="Bookmark" onClick={()=>bookmark(selectedWord.id)}><Bookmark fill={profile.bookmarks.includes(selectedWord.id)?'currentColor':'none'}/></button></div><div className="dimension-grid">{E.dimensions.map(d=><div key={d}><span>{dimNames[d]}</span><b>{E.dimensionScore(profile.wp[selectedWord.id],d)}%</b></div>)}</div></>}</DialogContent></Dialog>
 <AlertDialog open={resetOpen} onOpenChange={setResetOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Progress tozalansinmi?</AlertDialogTitle><AlertDialogDescription>So‘zlar mastery, xatolar va test natijalari tozalanadi. Avval zaxira yuklab olish tavsiya etiladi.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Bekor qilish</AlertDialogCancel><AlertDialogAction onClick={()=>{const p=E.newProfile(profile.firstName,profile.lastName);p.settings=profile.settings;update(p);setSession(null);setResetOpen(false);go('home');}}>Tozalash</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Toaster richColors position="top-center"/>
 </SidebarProvider>;
 function WordCard({w}:{w:Word}){return <button className="card vocab-card" onClick={()=>setSelectedWord(w)}><div className="row between"><span className="muted">Unit {w.unit}</span><span className="vocab-status">{levelNames[E.level(profile?.wp[w.id])]}</span></div><h3>{w.word}</h3><p>{w.uzbekMeaning}</p><Bar value={E.mastery(profile?.wp[w.id])}/><div className="row between"><small>{E.mastery(profile?.wp[w.id])}% mastery</small><Volume2 size={16}/></div></button>;}
}
